Update wf_Terraform.yml

diff --git a/.github/workflows/wf_Terraform.yml b/.github/workflows/wf_Terraform.yml
--- a/.github/workflows/wf_Terraform.yml
+++ b/.github/workflows/wf_Terraform.yml
@@ -27,8 +27,22 @@ jobs:
         run: terraform init
 
 
+      # - name: Terraform Format Check
+      #   run: terraform fmt -check
       - name: Terraform Format Check
-        run: terraform fmt -check
+        run: |
+          # Run terraform fmt -check and capture the output
+          OUTPUT=$(terraform fmt -check)
+          # Check if the exit code is 3, indicating files need formatting
+          if [ $? -eq 3 ]; then
+            echo "The following files need formatting:"
+            echo "$OUTPUT"
+            # Fail the step to stop the workflow and highlight the issue
+            exit 1
+          else
+            echo "All Terraform files are properly formatted."
+          fi
+
 
       - name: Terraform Validate
         run: terraform validate
